services:
  - type: web
    name: matcha-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn matcha_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: matcha-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: matcha-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - type: worker
    name: matcha-celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A matcha_backend worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: matcha-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: matcha-redis
          property: connectionString

  - type: redis
    name: matcha-redis
    ipAllowList: []
