# Generated by Django 5.2.15 on 2026-06-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Unknown Candidate', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_text', models.TextField(help_text='Full text extracted from the Resume PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField(help_text='Full text extracted from the JD PDF')),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_summary', models.TextField(blank=True, null=True)),
                ('skill_match_score', models.IntegerField(default=0)),
                ('skill_gap_analysis', models.JSONField(blank=True, default=dict, null=True)),
                ('interview_questions', models.JSONField(blank=True, default=list, null=True)),
                ('final_rank_score', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_report', to='core.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.jobdescription'),
        ),
    ]
