# Generated by Django 5.2.15 on 2026-06-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(default='', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobdescription'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_text',
            field=models.TextField(),
        ),
    ]
