# Generated by Django 5.2.15 on 2026-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uploaded_at_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
