# Generated by Django 5.2.15 on 2026-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='final_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
